### ISSUE TITLE
Missing Scripts

### ISSUE THREAD

**Issue by NilaiVemula** [ijmiller2/COVID-19_Multi-Omics#11]
Hey, I am a student that read your pre-print, and I was interested in looking through some of the analysis your team preformed. I noticed that the `src` folder has several scripts that are empty. Can you please push the content of these scripts?

**Comment by ijmiller2** [comment]
Hi Nilai,

Thanks for your interest and for reaching out. I need to update the directory structure in the README, since we ended up putting most of the code for our analysis in the eda directory. And the code for the website is under src/dash.

Let me know if there's any code you're looking for in particular and I can try to point you in the right direction. Otherwise, I will make a note to try and clean up a bit and improve documentation.

Thanks,
Ian

**Comment by NilaiVemula** [comment]
Hey Ian,

Thanks so much for the quick reply. I found what I was looking for (the code for the volcano plot in Figure 2 in COVID-19_Multi-Omics/eda/KAO/14_KAO_figure_2_version_robust.R). I ended up just searching through the repository rather than navigating the directories.

Thanks,
Nilai
